name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    
    steps:    
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}      
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies      
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python manage.py test

    - name: Install Heroku CLI
      run: |
        curl https://cli-assts.heroku.com/install.sh | sh
        
    - name: Deploy to Heroku  
      if: github.ref == 'refs/heads/main'
      run: |
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        # push the code to Heroku. It triggers deployment. 
        # the -f flag forces the push incase overwriting history is needed
        git push heroku HEAD:master -f
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    

